/* source-view.c generated by valac 0.10.0, the Vala compiler
 * generated from source-view.vala, do not modify */

/*
 * Copyright (c) 2010, Nate Stedman <natesm@gmail.com>
 * 
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define SOURCE_TYPE_BASE_VIEW (source_base_view_get_type ())
#define SOURCE_BASE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SOURCE_TYPE_BASE_VIEW, SourceBaseView))
#define SOURCE_BASE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SOURCE_TYPE_BASE_VIEW, SourceBaseViewClass))
#define SOURCE_IS_BASE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SOURCE_TYPE_BASE_VIEW))
#define SOURCE_IS_BASE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SOURCE_TYPE_BASE_VIEW))
#define SOURCE_BASE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SOURCE_TYPE_BASE_VIEW, SourceBaseViewClass))

typedef struct _SourceBaseView SourceBaseView;
typedef struct _SourceBaseViewClass SourceBaseViewClass;
typedef struct _SourceBaseViewPrivate SourceBaseViewPrivate;

#define SOURCE_TYPE_LIST (source_list_get_type ())
#define SOURCE_LIST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SOURCE_TYPE_LIST, SourceList))
#define SOURCE_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SOURCE_TYPE_LIST, SourceListClass))
#define SOURCE_IS_LIST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SOURCE_TYPE_LIST))
#define SOURCE_IS_LIST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SOURCE_TYPE_LIST))
#define SOURCE_LIST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SOURCE_TYPE_LIST, SourceListClass))

typedef struct _SourceList SourceList;
typedef struct _SourceListClass SourceListClass;

#define SOURCE_TYPE_VIEW (source_view_get_type ())
#define SOURCE_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SOURCE_TYPE_VIEW, SourceView))
#define SOURCE_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SOURCE_TYPE_VIEW, SourceViewClass))
#define SOURCE_IS_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SOURCE_TYPE_VIEW))
#define SOURCE_IS_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SOURCE_TYPE_VIEW))
#define SOURCE_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SOURCE_TYPE_VIEW, SourceViewClass))

typedef struct _SourceView SourceView;
typedef struct _SourceViewClass SourceViewClass;
typedef struct _SourceViewPrivate SourceViewPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _SourceBaseView {
	GtkAlignment parent_instance;
	SourceBaseViewPrivate * priv;
	GtkAlignment* bin;
	SourceList* list;
};

struct _SourceBaseViewClass {
	GtkAlignmentClass parent_class;
};

struct _SourceView {
	SourceBaseView parent_instance;
	SourceViewPrivate * priv;
};

struct _SourceViewClass {
	SourceBaseViewClass parent_class;
};


static gpointer source_view_parent_class = NULL;

GType source_base_view_get_type (void) G_GNUC_CONST;
GType source_list_get_type (void) G_GNUC_CONST;
GType source_view_get_type (void) G_GNUC_CONST;
enum  {
	SOURCE_VIEW_DUMMY_PROPERTY
};
SourceView* source_view_new (void);
SourceView* source_view_construct (GType object_type);
SourceBaseView* source_base_view_construct (GType object_type);



/**
 * Creates an empty Source.View. Add groups with add_group().
 */
#line 28 "source-view.vala"
SourceView* source_view_construct (GType object_type) {
#line 99 "source-view.c"
	SourceView * self;
	GtkHBox* hbox;
	GtkVSeparator* _tmp0_;
#line 31 "source-view.vala"
	self = (SourceView*) source_base_view_construct (object_type);
#line 34 "source-view.vala"
	hbox = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 0));
#line 35 "source-view.vala"
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) ((SourceBaseView*) self)->list, FALSE, FALSE, (guint) 0);
#line 36 "source-view.vala"
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) (_tmp0_ = g_object_ref_sink ((GtkVSeparator*) gtk_vseparator_new ())), FALSE, FALSE, (guint) 0);
#line 111 "source-view.c"
	_g_object_unref0 (_tmp0_);
#line 37 "source-view.vala"
	gtk_box_pack_start ((GtkBox*) hbox, (GtkWidget*) ((SourceBaseView*) self)->bin, TRUE, TRUE, (guint) 0);
#line 38 "source-view.vala"
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) hbox);
#line 117 "source-view.c"
	_g_object_unref0 (hbox);
	return self;
}


#line 28 "source-view.vala"
SourceView* source_view_new (void) {
#line 28 "source-view.vala"
	return source_view_construct (SOURCE_TYPE_VIEW);
#line 127 "source-view.c"
}


static void source_view_class_init (SourceViewClass * klass) {
	source_view_parent_class = g_type_class_peek_parent (klass);
}


static void source_view_instance_init (SourceView * self) {
}


/**
 * A simple implementation of a widget using {@link Source.List}.
 *
 * Source.View consists of a {@link Source.List}, a separator, and a Gtk.Bin
 * packed into a Gtk.HBox.
 */
GType source_view_get_type (void) {
	static volatile gsize source_view_type_id__volatile = 0;
	if (g_once_init_enter (&source_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SourceViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) source_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SourceView), 0, (GInstanceInitFunc) source_view_instance_init, NULL };
		GType source_view_type_id;
		source_view_type_id = g_type_register_static (SOURCE_TYPE_BASE_VIEW, "SourceView", &g_define_type_info, 0);
		g_once_init_leave (&source_view_type_id__volatile, source_view_type_id);
	}
	return source_view_type_id__volatile;
}




