/* ease-import-flickr-service.c generated by valac 0.10.0, the Vala compiler
 * generated from ease-import-flickr-service.vala, do not modify */

/*
  TODO :
  - escaping the description tags (or show the markup maybe?)
  - asyncing
  - getting licence and author's realname based on the IDs we get right now
  - make a nice combo-box for licenses
  - make the UI prettier
  - split out in a common Ease.ResourceImporter dialog or something
  - raise accuracy (ie use the keywords to search tags _and_ description, and others) 50% DONE
  - get the next set of photos (use the "page" param of flickr.photos.search)
  - show a tiny spinner when loading
*/

#include <glib.h>
#include <glib-object.h>
#include <ease-core.h>
#include <json-glib/json-glib.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <rest/rest-proxy.h>
#include <rest-extras/flickr-proxy.h>
#include <rest/rest-proxy-call.h>
#include <glib/gi18n-lib.h>
#include <float.h>
#include <math.h>


#define EASE_TYPE_FLICKR_SERVICE (ease_flickr_service_get_type ())
#define EASE_FLICKR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EASE_TYPE_FLICKR_SERVICE, EaseFlickrService))
#define EASE_FLICKR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EASE_TYPE_FLICKR_SERVICE, EaseFlickrServiceClass))
#define EASE_IS_FLICKR_SERVICE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EASE_TYPE_FLICKR_SERVICE))
#define EASE_IS_FLICKR_SERVICE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EASE_TYPE_FLICKR_SERVICE))
#define EASE_FLICKR_SERVICE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EASE_TYPE_FLICKR_SERVICE, EaseFlickrServiceClass))

typedef struct _EaseFlickrService EaseFlickrService;
typedef struct _EaseFlickrServiceClass EaseFlickrServiceClass;
typedef struct _EaseFlickrServicePrivate EaseFlickrServicePrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _json_array_unref0(var) ((var == NULL) ? NULL : (var = (json_array_unref (var), NULL)))

#define EASE_TYPE_FLICKR_MEDIA (ease_flickr_media_get_type ())
#define EASE_FLICKR_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EASE_TYPE_FLICKR_MEDIA, EaseFlickrMedia))
#define EASE_FLICKR_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EASE_TYPE_FLICKR_MEDIA, EaseFlickrMediaClass))
#define EASE_IS_FLICKR_MEDIA(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EASE_TYPE_FLICKR_MEDIA))
#define EASE_IS_FLICKR_MEDIA_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EASE_TYPE_FLICKR_MEDIA))
#define EASE_FLICKR_MEDIA_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EASE_TYPE_FLICKR_MEDIA, EaseFlickrMediaClass))

typedef struct _EaseFlickrMedia EaseFlickrMedia;
typedef struct _EaseFlickrMediaClass EaseFlickrMediaClass;
typedef struct _EaseFlickrMediaPrivate EaseFlickrMediaPrivate;

struct _EaseFlickrService {
	EasePluginImportService parent_instance;
	EaseFlickrServicePrivate * priv;
};

struct _EaseFlickrServiceClass {
	EasePluginImportServiceClass parent_class;
};

struct _EaseFlickrServicePrivate {
	JsonParser* parser;
	GtkCheckButton* share_alike;
	GtkCheckButton* for_commercial;
};

struct _EaseFlickrMedia {
	EasePluginImportMedia parent_instance;
	EaseFlickrMediaPrivate * priv;
	char* title;
	char* description;
	char* author;
};

struct _EaseFlickrMediaClass {
	EasePluginImportMediaClass parent_class;
};


static gpointer ease_flickr_service_parent_class = NULL;

GType ease_flickr_service_get_type (void) G_GNUC_CONST;
#define EASE_FLICKR_SERVICE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EASE_TYPE_FLICKR_SERVICE, EaseFlickrServicePrivate))
enum  {
	EASE_FLICKR_SERVICE_DUMMY_PROPERTY
};
#define EASE_FLICKR_SERVICE_api_key "17c40bceda03e0d6f947b001e7c62058"
#define EASE_FLICKR_SERVICE_secret "a7c16179a409418b"
#define EASE_FLICKR_SERVICE_URL_FORMAT "http://farm%i.static.flickr.com/%s/%s_%s.jpg"
#define EASE_FLICKR_SERVICE_CC_BY "4,"
#define EASE_FLICKR_SERVICE_CC_BY_NC "2,"
#define EASE_FLICKR_SERVICE_CC_BY_NC_SA "1,"
#define EASE_FLICKR_SERVICE_CC_BY_SA "5,"
static RestProxy* ease_flickr_service_real_create_proxy (EasePluginImportService* base);
static RestProxyCall* ease_flickr_service_real_create_call (EasePluginImportService* base, RestProxy* proxy, const char* search);
static GtkWidget* ease_flickr_service_real_extra_widget (EasePluginImportService* base);
static void ease_flickr_service_real_parse_data (EasePluginImportService* base, const char* jsondata);
static void _lambda70_ (JsonArray* array, guint index, JsonNode* element, EaseFlickrService* self);
void ease_flickr_service_iconview_add_thumbnail_from_json (EaseFlickrService* self, JsonArray* array, guint index, JsonNode* element);
static void __lambda70__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self);
EaseFlickrMedia* ease_flickr_media_new (void);
EaseFlickrMedia* ease_flickr_media_construct (GType object_type);
GType ease_flickr_media_get_type (void) G_GNUC_CONST;
EaseFlickrService* ease_flickr_service_new (void);
EaseFlickrService* ease_flickr_service_construct (GType object_type);
static void ease_flickr_service_finalize (GObject* obj);
static int _vala_strcmp0 (const char * str1, const char * str2);



#line 35 "ease-import-flickr-service.vala"
static RestProxy* ease_flickr_service_real_create_proxy (EasePluginImportService* base) {
#line 121 "ease-import-flickr-service.c"
	EaseFlickrService * self;
	RestProxy* result = NULL;
	self = (EaseFlickrService*) base;
	result = (RestProxy*) ((FlickrProxy*) flickr_proxy_new (EASE_FLICKR_SERVICE_api_key, EASE_FLICKR_SERVICE_secret));
#line 37 "ease-import-flickr-service.vala"
	return result;
#line 128 "ease-import-flickr-service.c"
}


static glong string_get_length (const char* self) {
	glong result;
	g_return_val_if_fail (self != NULL, 0L);
	result = g_utf8_strlen (self, (gssize) (-1));
#line 1170 "glib-2.0.vapi"
	return result;
#line 138 "ease-import-flickr-service.c"
}


#line 1086 "glib-2.0.vapi"
static char* string_substring (const char* self, glong offset, glong len) {
#line 144 "ease-import-flickr-service.c"
	char* result = NULL;
	glong string_length;
	const char* start;
#line 1086 "glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1087 "glib-2.0.vapi"
	string_length = string_get_length (self);
#line 1088 "glib-2.0.vapi"
	if (offset < 0) {
#line 1089 "glib-2.0.vapi"
		offset = string_length + offset;
#line 1090 "glib-2.0.vapi"
		g_return_val_if_fail (offset >= 0, NULL);
#line 158 "ease-import-flickr-service.c"
	} else {
#line 1092 "glib-2.0.vapi"
		g_return_val_if_fail (offset <= string_length, NULL);
#line 162 "ease-import-flickr-service.c"
	}
#line 1094 "glib-2.0.vapi"
	if (len < 0) {
#line 1095 "glib-2.0.vapi"
		len = string_length - offset;
#line 168 "ease-import-flickr-service.c"
	}
#line 1097 "glib-2.0.vapi"
	g_return_val_if_fail ((offset + len) <= string_length, NULL);
#line 1098 "glib-2.0.vapi"
	start = g_utf8_offset_to_pointer (self, offset);
#line 174 "ease-import-flickr-service.c"
	result = g_strndup (start, ((gchar*) g_utf8_offset_to_pointer (start, len)) - ((gchar*) start));
#line 1099 "glib-2.0.vapi"
	return result;
#line 178 "ease-import-flickr-service.c"
}


#line 40 "ease-import-flickr-service.vala"
static RestProxyCall* ease_flickr_service_real_create_call (EasePluginImportService* base, RestProxy* proxy, const char* search) {
#line 184 "ease-import-flickr-service.c"
	EaseFlickrService * self;
	RestProxyCall* result = NULL;
	char* licenses;
	RestProxyCall* call;
	char* _tmp4_;
	self = (EaseFlickrService*) base;
#line 40 "ease-import-flickr-service.vala"
	g_return_val_if_fail (proxy != NULL, NULL);
#line 40 "ease-import-flickr-service.vala"
	g_return_val_if_fail (search != NULL, NULL);
#line 195 "ease-import-flickr-service.c"
	licenses = NULL;
#line 44 "ease-import-flickr-service.vala"
	if (gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->share_alike)) {
#line 199 "ease-import-flickr-service.c"
		char* _tmp0_;
#line 46 "ease-import-flickr-service.vala"
		licenses = (_tmp0_ = g_strdup (EASE_FLICKR_SERVICE_CC_BY_SA), _g_free0 (licenses), _tmp0_);
#line 47 "ease-import-flickr-service.vala"
		if (!gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->for_commercial)) {
#line 205 "ease-import-flickr-service.c"
			char* _tmp1_;
#line 47 "ease-import-flickr-service.vala"
			licenses = (_tmp1_ = g_strconcat (licenses, EASE_FLICKR_SERVICE_CC_BY_NC_SA, NULL), _g_free0 (licenses), _tmp1_);
#line 209 "ease-import-flickr-service.c"
		}
	} else {
		char* _tmp2_;
#line 51 "ease-import-flickr-service.vala"
		licenses = (_tmp2_ = g_strdup (EASE_FLICKR_SERVICE_CC_BY), _g_free0 (licenses), _tmp2_);
#line 52 "ease-import-flickr-service.vala"
		if (!gtk_toggle_button_get_active ((GtkToggleButton*) self->priv->for_commercial)) {
#line 217 "ease-import-flickr-service.c"
			char* _tmp3_;
#line 52 "ease-import-flickr-service.vala"
			licenses = (_tmp3_ = g_strconcat (licenses, EASE_FLICKR_SERVICE_CC_BY_NC, NULL), _g_free0 (licenses), _tmp3_);
#line 221 "ease-import-flickr-service.c"
		}
	}
#line 55 "ease-import-flickr-service.vala"
	call = rest_proxy_new_call (proxy);
#line 56 "ease-import-flickr-service.vala"
	rest_proxy_call_set_function (call, "flickr.photos.search");
#line 57 "ease-import-flickr-service.vala"
	rest_proxy_call_add_params (call, "tags", search, "tag_mode", "all", "per_page", "10", "format", "json", "sort", "relevance", "nojsoncallback", "1", "license", _tmp4_ = string_substring (licenses, (glong) 0, string_get_length (licenses) - 1), "extras", "description,license", NULL, NULL);
#line 230 "ease-import-flickr-service.c"
	_g_free0 (_tmp4_);
	result = call;
	_g_free0 (licenses);
#line 71 "ease-import-flickr-service.vala"
	return result;
#line 236 "ease-import-flickr-service.c"
}


#line 74 "ease-import-flickr-service.vala"
static GtkWidget* ease_flickr_service_real_extra_widget (EasePluginImportService* base) {
#line 242 "ease-import-flickr-service.c"
	EaseFlickrService * self;
	GtkWidget* result = NULL;
	GtkHBox* box;
	GtkCheckButton* _tmp0_;
	GtkCheckButton* _tmp1_;
	self = (EaseFlickrService*) base;
#line 77 "ease-import-flickr-service.vala"
	box = g_object_ref_sink ((GtkHBox*) gtk_hbox_new (FALSE, 4));
#line 80 "ease-import-flickr-service.vala"
	self->priv->share_alike = (_tmp0_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label (_ ("Share Alike"))), _g_object_unref0 (self->priv->share_alike), _tmp0_);
#line 81 "ease-import-flickr-service.vala"
	self->priv->for_commercial = (_tmp1_ = g_object_ref_sink ((GtkCheckButton*) gtk_check_button_new_with_label (_ ("For Commercial Use"))), _g_object_unref0 (self->priv->for_commercial), _tmp1_);
#line 85 "ease-import-flickr-service.vala"
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) self->priv->share_alike, FALSE, FALSE, (guint) 0);
#line 86 "ease-import-flickr-service.vala"
	gtk_box_pack_start ((GtkBox*) box, (GtkWidget*) self->priv->for_commercial, FALSE, FALSE, (guint) 0);
#line 259 "ease-import-flickr-service.c"
	result = (GtkWidget*) box;
#line 88 "ease-import-flickr-service.vala"
	return result;
#line 263 "ease-import-flickr-service.c"
}


static gpointer _json_object_ref0 (gpointer self) {
	return self ? json_object_ref (self) : NULL;
}


static gpointer _json_array_ref0 (gpointer self) {
	return self ? json_array_ref (self) : NULL;
}


#line 119 "ease-import-flickr-service.vala"
static void _lambda70_ (JsonArray* array, guint index, JsonNode* element, EaseFlickrService* self) {
#line 119 "ease-import-flickr-service.vala"
	g_return_if_fail (array != NULL);
#line 119 "ease-import-flickr-service.vala"
	g_return_if_fail (element != NULL);
#line 120 "ease-import-flickr-service.vala"
	ease_flickr_service_iconview_add_thumbnail_from_json (self, array, index, element);
#line 285 "ease-import-flickr-service.c"
}


#line 119 "ease-import-flickr-service.vala"
static void __lambda70__json_array_foreach (JsonArray* array, guint index_, JsonNode* element_node, gpointer self) {
#line 291 "ease-import-flickr-service.c"
	_lambda70_ (array, index_, element_node, self);
}


#line 91 "ease-import-flickr-service.vala"
static void ease_flickr_service_real_parse_data (EasePluginImportService* base, const char* jsondata) {
#line 298 "ease-import-flickr-service.c"
	EaseFlickrService * self;
	JsonObject* obj;
	char* stat;
	JsonObject* photos;
	JsonArray* photo_array;
	GError * _inner_error_ = NULL;
	self = (EaseFlickrService*) base;
#line 91 "ease-import-flickr-service.vala"
	g_return_if_fail (jsondata != NULL);
#line 93 "ease-import-flickr-service.vala"
	if (jsondata == NULL) {
#line 93 "ease-import-flickr-service.vala"
		return;
#line 312 "ease-import-flickr-service.c"
	}
	{
#line 97 "ease-import-flickr-service.vala"
		json_parser_load_from_data (self->priv->parser, jsondata, -1, &_inner_error_);
#line 317 "ease-import-flickr-service.c"
		if (_inner_error_ != NULL) {
			goto __catch7_g_error;
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		GError * e;
		e = _inner_error_;
		_inner_error_ = NULL;
		{
#line 101 "ease-import-flickr-service.vala"
			g_error ("ease-import-flickr-service.vala:101: Couldn't parse JSON data: %s", e->message);
#line 331 "ease-import-flickr-service.c"
			_g_error_free0 (e);
		}
	}
	__finally7:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
#line 104 "ease-import-flickr-service.vala"
	obj = _json_object_ref0 (json_node_get_object (json_parser_get_root (self->priv->parser)));
#line 106 "ease-import-flickr-service.vala"
	stat = g_strdup (json_object_get_string_member (obj, "stat"));
#line 107 "ease-import-flickr-service.vala"
	if (_vala_strcmp0 (stat, "ok") != 0) {
#line 109 "ease-import-flickr-service.vala"
		g_warning ("ease-import-flickr-service.vala:109: The request failed : \n" \
"Error code: %G\n" \
"Message: %s", (double) json_object_get_int_member (obj, "code"), json_object_get_string_member (obj, "message"));
#line 349 "ease-import-flickr-service.c"
		_g_free0 (stat);
		_json_object_unref0 (obj);
#line 112 "ease-import-flickr-service.vala"
		return;
#line 354 "ease-import-flickr-service.c"
	}
#line 115 "ease-import-flickr-service.vala"
	photos = _json_object_ref0 (json_object_get_object_member (obj, "photos"));
#line 116 "ease-import-flickr-service.vala"
	photo_array = _json_array_ref0 (json_object_get_array_member (photos, "photo"));
#line 119 "ease-import-flickr-service.vala"
	json_array_foreach_element (photo_array, __lambda70__json_array_foreach, self);
#line 362 "ease-import-flickr-service.c"
	_json_array_unref0 (photo_array);
	_json_object_unref0 (photos);
	_g_free0 (stat);
	_json_object_unref0 (obj);
}


#line 124 "ease-import-flickr-service.vala"
void ease_flickr_service_iconview_add_thumbnail_from_json (EaseFlickrService* self, JsonArray* array, guint index, JsonNode* element) {
#line 372 "ease-import-flickr-service.c"
	JsonObject* photo;
	gint64 farm;
	char* secret;
	char* server;
	char* id;
	EaseFlickrMedia* image;
	char* _tmp0_;
	char* _tmp1_;
	char* _tmp2_;
	char* _tmp3_;
	char* _tmp4_;
#line 124 "ease-import-flickr-service.vala"
	g_return_if_fail (self != NULL);
#line 124 "ease-import-flickr-service.vala"
	g_return_if_fail (array != NULL);
#line 124 "ease-import-flickr-service.vala"
	g_return_if_fail (element != NULL);
#line 128 "ease-import-flickr-service.vala"
	photo = _json_object_ref0 (json_node_get_object (element));
#line 129 "ease-import-flickr-service.vala"
	farm = json_object_get_int_member (photo, "farm");
#line 130 "ease-import-flickr-service.vala"
	secret = g_strdup (json_object_get_string_member (photo, "secret"));
#line 131 "ease-import-flickr-service.vala"
	server = g_strdup (json_object_get_string_member (photo, "server"));
#line 132 "ease-import-flickr-service.vala"
	id = g_strdup (json_object_get_string_member (photo, "id"));
#line 134 "ease-import-flickr-service.vala"
	image = ease_flickr_media_new ();
#line 135 "ease-import-flickr-service.vala"
	((EasePluginImportMedia*) image)->file_link = (_tmp0_ = g_strdup_printf (EASE_FLICKR_SERVICE_URL_FORMAT, farm, server, id, secret, "z"), _g_free0 (((EasePluginImportMedia*) image)->file_link), _tmp0_);
#line 136 "ease-import-flickr-service.vala"
	((EasePluginImportMedia*) image)->thumb_link = (_tmp1_ = g_strdup_printf (EASE_FLICKR_SERVICE_URL_FORMAT, farm, server, id, secret, "m"), _g_free0 (((EasePluginImportMedia*) image)->thumb_link), _tmp1_);
#line 139 "ease-import-flickr-service.vala"
	image->title = (_tmp2_ = g_strdup (json_object_get_string_member (photo, "title")), _g_free0 (image->title), _tmp2_);
#line 140 "ease-import-flickr-service.vala"
	image->description = (_tmp3_ = g_strdup (json_object_get_string_member (json_object_get_object_member (photo, "description"), "_content")), _g_free0 (image->description), _tmp3_);
#line 143 "ease-import-flickr-service.vala"
	image->author = (_tmp4_ = g_strdup (json_object_get_string_member (photo, "owner")), _g_free0 (image->author), _tmp4_);
#line 145 "ease-import-flickr-service.vala"
	ease_plugin_import_service_add_media ((EasePluginImportService*) self, (EasePluginImportMedia*) image);
#line 414 "ease-import-flickr-service.c"
	_g_object_unref0 (image);
	_g_free0 (id);
	_g_free0 (server);
	_g_free0 (secret);
	_json_object_unref0 (photo);
}


#line 14 "ease-import-flickr-service.vala"
EaseFlickrService* ease_flickr_service_construct (GType object_type) {
#line 425 "ease-import-flickr-service.c"
	EaseFlickrService * self;
#line 14 "ease-import-flickr-service.vala"
	self = (EaseFlickrService*) ease_plugin_import_service_construct (object_type);
#line 429 "ease-import-flickr-service.c"
	return self;
}


#line 14 "ease-import-flickr-service.vala"
EaseFlickrService* ease_flickr_service_new (void) {
#line 14 "ease-import-flickr-service.vala"
	return ease_flickr_service_construct (EASE_TYPE_FLICKR_SERVICE);
#line 438 "ease-import-flickr-service.c"
}


static void ease_flickr_service_class_init (EaseFlickrServiceClass * klass) {
	ease_flickr_service_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (EaseFlickrServicePrivate));
	EASE_PLUGIN_IMPORT_SERVICE_CLASS (klass)->create_proxy = ease_flickr_service_real_create_proxy;
	EASE_PLUGIN_IMPORT_SERVICE_CLASS (klass)->create_call = ease_flickr_service_real_create_call;
	EASE_PLUGIN_IMPORT_SERVICE_CLASS (klass)->extra_widget = ease_flickr_service_real_extra_widget;
	EASE_PLUGIN_IMPORT_SERVICE_CLASS (klass)->parse_data = ease_flickr_service_real_parse_data;
	G_OBJECT_CLASS (klass)->finalize = ease_flickr_service_finalize;
}


static void ease_flickr_service_instance_init (EaseFlickrService * self) {
	self->priv = EASE_FLICKR_SERVICE_GET_PRIVATE (self);
	self->priv->parser = json_parser_new ();
}


static void ease_flickr_service_finalize (GObject* obj) {
	EaseFlickrService * self;
	self = EASE_FLICKR_SERVICE (obj);
	_g_object_unref0 (self->priv->parser);
	_g_object_unref0 (self->priv->share_alike);
	_g_object_unref0 (self->priv->for_commercial);
	G_OBJECT_CLASS (ease_flickr_service_parent_class)->finalize (obj);
}


GType ease_flickr_service_get_type (void) {
	static volatile gsize ease_flickr_service_type_id__volatile = 0;
	if (g_once_init_enter (&ease_flickr_service_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EaseFlickrServiceClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ease_flickr_service_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EaseFlickrService), 0, (GInstanceInitFunc) ease_flickr_service_instance_init, NULL };
		GType ease_flickr_service_type_id;
		ease_flickr_service_type_id = g_type_register_static (EASE_PLUGIN_TYPE_IMPORT_SERVICE, "EaseFlickrService", &g_define_type_info, 0);
		g_once_init_leave (&ease_flickr_service_type_id__volatile, ease_flickr_service_type_id);
	}
	return ease_flickr_service_type_id__volatile;
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




