/* ease-iterable-models.c generated by valac 0.10.0, the Vala compiler
 * generated from ease-iterable-models.vala, do not modify */

/*  Ease, a GTK presentation application
    Copyright (C) 2010 Nate Stedman

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gobject/gvaluecollector.h>


#define EASE_TYPE_ITERABLE_TREE_MODEL (ease_iterable_tree_model_get_type ())
#define EASE_ITERABLE_TREE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EASE_TYPE_ITERABLE_TREE_MODEL, EaseIterableTreeModel))
#define EASE_IS_ITERABLE_TREE_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EASE_TYPE_ITERABLE_TREE_MODEL))
#define EASE_ITERABLE_TREE_MODEL_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), EASE_TYPE_ITERABLE_TREE_MODEL, EaseIterableTreeModelIface))

typedef struct _EaseIterableTreeModel EaseIterableTreeModel;
typedef struct _EaseIterableTreeModelIface EaseIterableTreeModelIface;

#define EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR (ease_iterable_tree_model_iterator_get_type ())
#define EASE_ITERABLE_TREE_MODEL_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR, EaseIterableTreeModelIterator))
#define EASE_ITERABLE_TREE_MODEL_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR, EaseIterableTreeModelIteratorClass))
#define EASE_ITERABLE_TREE_MODEL_IS_ITERATOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR))
#define EASE_ITERABLE_TREE_MODEL_IS_ITERATOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR))
#define EASE_ITERABLE_TREE_MODEL_ITERATOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR, EaseIterableTreeModelIteratorClass))

typedef struct _EaseIterableTreeModelIterator EaseIterableTreeModelIterator;
typedef struct _EaseIterableTreeModelIteratorClass EaseIterableTreeModelIteratorClass;
typedef struct _EaseIterableTreeModelIteratorPrivate EaseIterableTreeModelIteratorPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _EaseIterableTreeModelParamSpecIterator EaseIterableTreeModelParamSpecIterator;

#define EASE_TYPE_ITERABLE_LIST_STORE (ease_iterable_list_store_get_type ())
#define EASE_ITERABLE_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), EASE_TYPE_ITERABLE_LIST_STORE, EaseIterableListStore))
#define EASE_ITERABLE_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), EASE_TYPE_ITERABLE_LIST_STORE, EaseIterableListStoreClass))
#define EASE_IS_ITERABLE_LIST_STORE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), EASE_TYPE_ITERABLE_LIST_STORE))
#define EASE_IS_ITERABLE_LIST_STORE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), EASE_TYPE_ITERABLE_LIST_STORE))
#define EASE_ITERABLE_LIST_STORE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), EASE_TYPE_ITERABLE_LIST_STORE, EaseIterableListStoreClass))

typedef struct _EaseIterableListStore EaseIterableListStore;
typedef struct _EaseIterableListStoreClass EaseIterableListStoreClass;
typedef struct _EaseIterableListStorePrivate EaseIterableListStorePrivate;

struct _EaseIterableTreeModelIface {
	GTypeInterface parent_iface;
};

struct _EaseIterableTreeModelIterator {
	GTypeInstance parent_instance;
	volatile int ref_count;
	EaseIterableTreeModelIteratorPrivate * priv;
};

struct _EaseIterableTreeModelIteratorClass {
	GTypeClass parent_class;
	void (*finalize) (EaseIterableTreeModelIterator *self);
};

struct _EaseIterableTreeModelIteratorPrivate {
	GtkTreeIter itr;
	EaseIterableTreeModel* model;
	gboolean more;
};

struct _EaseIterableTreeModelParamSpecIterator {
	GParamSpec parent_instance;
};

struct _EaseIterableListStore {
	GtkListStore parent_instance;
	EaseIterableListStorePrivate * priv;
};

struct _EaseIterableListStoreClass {
	GtkListStoreClass parent_class;
};


static gpointer ease_iterable_tree_model_iterator_parent_class = NULL;
static gpointer ease_iterable_list_store_parent_class = NULL;
static EaseIterableTreeModelIface* ease_iterable_list_store_ease_iterable_tree_model_parent_iface = NULL;

GType ease_iterable_tree_model_get_type (void) G_GNUC_CONST;
gpointer ease_iterable_tree_model_iterator_ref (gpointer instance);
void ease_iterable_tree_model_iterator_unref (gpointer instance);
GParamSpec* ease_iterable_tree_model_param_spec_iterator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void ease_iterable_tree_model_value_set_iterator (GValue* value, gpointer v_object);
void ease_iterable_tree_model_value_take_iterator (GValue* value, gpointer v_object);
gpointer ease_iterable_tree_model_value_get_iterator (const GValue* value);
GType ease_iterable_tree_model_iterator_get_type (void) G_GNUC_CONST;
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator (EaseIterableTreeModel* self);
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator_new (EaseIterableTreeModel* _self_);
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator_construct (GType object_type, EaseIterableTreeModel* _self_);
void ease_iterable_tree_model_index (EaseIterableTreeModel* self, gint index, GtkTreeIter* result);
#define EASE_ITERABLE_TREE_MODEL_ITERATOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR, EaseIterableTreeModelIteratorPrivate))
enum  {
	EASE_ITERABLE_TREE_MODEL_ITERATOR_DUMMY_PROPERTY
};
gboolean ease_iterable_tree_model_iterator_next (EaseIterableTreeModelIterator* self);
void ease_iterable_tree_model_iterator_get (EaseIterableTreeModelIterator* self, GtkTreeIter* result);
static void ease_iterable_tree_model_iterator_finalize (EaseIterableTreeModelIterator* obj);
GType ease_iterable_list_store_get_type (void) G_GNUC_CONST;
enum  {
	EASE_ITERABLE_LIST_STORE_DUMMY_PROPERTY,
	EASE_ITERABLE_LIST_STORE_SIZE
};
EaseIterableListStore* ease_iterable_list_store_new (GType* types, int types_length1);
EaseIterableListStore* ease_iterable_list_store_construct (GType object_type, GType* types, int types_length1);
gint ease_iterable_list_store_get_size (EaseIterableListStore* self);
static void ease_iterable_list_store_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);



#line 26 "ease-iterable-models.vala"
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator (EaseIterableTreeModel* self) {
#line 132 "ease-iterable-models.c"
	EaseIterableTreeModelIterator* result = NULL;
	result = ease_iterable_tree_model_iterator_new (self);
#line 28 "ease-iterable-models.vala"
	return result;
#line 137 "ease-iterable-models.c"
}


#line 31 "ease-iterable-models.vala"
void ease_iterable_tree_model_index (EaseIterableTreeModel* self, gint index, GtkTreeIter* result) {
#line 143 "ease-iterable-models.c"
	GtkTreeIter itr = {0};
#line 34 "ease-iterable-models.vala"
	gtk_tree_model_iter_nth_child ((GtkTreeModel*) self, &itr, NULL, index);
#line 147 "ease-iterable-models.c"
	*result = itr;
#line 35 "ease-iterable-models.vala"
	return;
#line 151 "ease-iterable-models.c"
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


#line 44 "ease-iterable-models.vala"
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator_construct (GType object_type, EaseIterableTreeModel* _self_) {
#line 162 "ease-iterable-models.c"
	EaseIterableTreeModelIterator* self;
	EaseIterableTreeModel* _tmp0_;
#line 44 "ease-iterable-models.vala"
	g_return_val_if_fail (_self_ != NULL, NULL);
#line 167 "ease-iterable-models.c"
	self = (EaseIterableTreeModelIterator*) g_type_create_instance (object_type);
#line 46 "ease-iterable-models.vala"
	self->priv->more = gtk_tree_model_get_iter_first ((GtkTreeModel*) _self_, &self->priv->itr);
#line 47 "ease-iterable-models.vala"
	self->priv->model = (_tmp0_ = _g_object_ref0 (_self_), _g_object_unref0 (self->priv->model), _tmp0_);
#line 173 "ease-iterable-models.c"
	return self;
}


#line 44 "ease-iterable-models.vala"
EaseIterableTreeModelIterator* ease_iterable_tree_model_iterator_new (EaseIterableTreeModel* _self_) {
#line 44 "ease-iterable-models.vala"
	return ease_iterable_tree_model_iterator_construct (EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR, _self_);
#line 182 "ease-iterable-models.c"
}


#line 50 "ease-iterable-models.vala"
gboolean ease_iterable_tree_model_iterator_next (EaseIterableTreeModelIterator* self) {
#line 188 "ease-iterable-models.c"
	gboolean result = FALSE;
#line 50 "ease-iterable-models.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 192 "ease-iterable-models.c"
	result = self->priv->more;
#line 52 "ease-iterable-models.vala"
	return result;
#line 196 "ease-iterable-models.c"
}


#line 55 "ease-iterable-models.vala"
void ease_iterable_tree_model_iterator_get (EaseIterableTreeModelIterator* self, GtkTreeIter* result) {
#line 202 "ease-iterable-models.c"
	GtkTreeIter ret;
#line 55 "ease-iterable-models.vala"
	g_return_if_fail (self != NULL);
#line 57 "ease-iterable-models.vala"
	ret = self->priv->itr;
#line 58 "ease-iterable-models.vala"
	self->priv->more = gtk_tree_model_iter_next ((GtkTreeModel*) self->priv->model, &self->priv->itr);
#line 210 "ease-iterable-models.c"
	*result = ret;
#line 59 "ease-iterable-models.vala"
	return;
#line 214 "ease-iterable-models.c"
}


static void ease_iterable_tree_model_value_iterator_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void ease_iterable_tree_model_value_iterator_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		ease_iterable_tree_model_iterator_unref (value->data[0].v_pointer);
	}
}


static void ease_iterable_tree_model_value_iterator_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = ease_iterable_tree_model_iterator_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer ease_iterable_tree_model_value_iterator_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* ease_iterable_tree_model_value_iterator_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		EaseIterableTreeModelIterator* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = ease_iterable_tree_model_iterator_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* ease_iterable_tree_model_value_iterator_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	EaseIterableTreeModelIterator** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = ease_iterable_tree_model_iterator_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* ease_iterable_tree_model_param_spec_iterator (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	EaseIterableTreeModelParamSpecIterator* spec;
	g_return_val_if_fail (g_type_is_a (object_type, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer ease_iterable_tree_model_value_get_iterator (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR), NULL);
	return value->data[0].v_pointer;
}


void ease_iterable_tree_model_value_set_iterator (GValue* value, gpointer v_object) {
	EaseIterableTreeModelIterator* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		ease_iterable_tree_model_iterator_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		ease_iterable_tree_model_iterator_unref (old);
	}
}


void ease_iterable_tree_model_value_take_iterator (GValue* value, gpointer v_object) {
	EaseIterableTreeModelIterator* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, EASE_ITERABLE_TREE_MODEL_TYPE_ITERATOR));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		ease_iterable_tree_model_iterator_unref (old);
	}
}


static void ease_iterable_tree_model_iterator_class_init (EaseIterableTreeModelIteratorClass * klass) {
	ease_iterable_tree_model_iterator_parent_class = g_type_class_peek_parent (klass);
	EASE_ITERABLE_TREE_MODEL_ITERATOR_CLASS (klass)->finalize = ease_iterable_tree_model_iterator_finalize;
	g_type_class_add_private (klass, sizeof (EaseIterableTreeModelIteratorPrivate));
}


static void ease_iterable_tree_model_iterator_instance_init (EaseIterableTreeModelIterator * self) {
	self->priv = EASE_ITERABLE_TREE_MODEL_ITERATOR_GET_PRIVATE (self);
	self->ref_count = 1;
}


static void ease_iterable_tree_model_iterator_finalize (EaseIterableTreeModelIterator* obj) {
	EaseIterableTreeModelIterator * self;
	self = EASE_ITERABLE_TREE_MODEL_ITERATOR (obj);
	_g_object_unref0 (self->priv->model);
}


GType ease_iterable_tree_model_iterator_get_type (void) {
	static volatile gsize ease_iterable_tree_model_iterator_type_id__volatile = 0;
	if (g_once_init_enter (&ease_iterable_tree_model_iterator_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { ease_iterable_tree_model_value_iterator_init, ease_iterable_tree_model_value_iterator_free_value, ease_iterable_tree_model_value_iterator_copy_value, ease_iterable_tree_model_value_iterator_peek_pointer, "p", ease_iterable_tree_model_value_iterator_collect_value, "p", ease_iterable_tree_model_value_iterator_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (EaseIterableTreeModelIteratorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ease_iterable_tree_model_iterator_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EaseIterableTreeModelIterator), 0, (GInstanceInitFunc) ease_iterable_tree_model_iterator_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType ease_iterable_tree_model_iterator_type_id;
		ease_iterable_tree_model_iterator_type_id = g_type_register_fundamental (g_type_fundamental_next (), "EaseIterableTreeModelIterator", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&ease_iterable_tree_model_iterator_type_id__volatile, ease_iterable_tree_model_iterator_type_id);
	}
	return ease_iterable_tree_model_iterator_type_id__volatile;
}


gpointer ease_iterable_tree_model_iterator_ref (gpointer instance) {
	EaseIterableTreeModelIterator* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void ease_iterable_tree_model_iterator_unref (gpointer instance) {
	EaseIterableTreeModelIterator* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		EASE_ITERABLE_TREE_MODEL_ITERATOR_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void ease_iterable_tree_model_base_init (EaseIterableTreeModelIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


/**
 * A Gtk.TreeModel iterable through "foreach".
 *
 * The foreach loop returns a Gtk.TreeIter. The Gtk.TreePath provided by the 
 * built in TreeModel foreach function is not (immediately) available.
 */
GType ease_iterable_tree_model_get_type (void) {
	static volatile gsize ease_iterable_tree_model_type_id__volatile = 0;
	if (g_once_init_enter (&ease_iterable_tree_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EaseIterableTreeModelIface), (GBaseInitFunc) ease_iterable_tree_model_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType ease_iterable_tree_model_type_id;
		ease_iterable_tree_model_type_id = g_type_register_static (G_TYPE_INTERFACE, "EaseIterableTreeModel", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (ease_iterable_tree_model_type_id, GTK_TYPE_TREE_MODEL);
		g_once_init_leave (&ease_iterable_tree_model_type_id__volatile, ease_iterable_tree_model_type_id);
	}
	return ease_iterable_tree_model_type_id__volatile;
}


/**
 * Creates an iterable ListStore with the specified types.
 */
#line 72 "ease-iterable-models.vala"
EaseIterableListStore* ease_iterable_list_store_construct (GType object_type, GType* types, int types_length1) {
#line 412 "ease-iterable-models.c"
	EaseIterableListStore * self;
	self = g_object_newv (object_type, 0, NULL);
#line 74 "ease-iterable-models.vala"
	gtk_list_store_set_column_types ((GtkListStore*) self, types_length1, types);
#line 417 "ease-iterable-models.c"
	return self;
}


#line 72 "ease-iterable-models.vala"
EaseIterableListStore* ease_iterable_list_store_new (GType* types, int types_length1) {
#line 72 "ease-iterable-models.vala"
	return ease_iterable_list_store_construct (EASE_TYPE_ITERABLE_LIST_STORE, types, types_length1);
#line 426 "ease-iterable-models.c"
}


gint ease_iterable_list_store_get_size (EaseIterableListStore* self) {
	gint result;
	g_return_val_if_fail (self != NULL, 0);
	result = gtk_tree_model_iter_n_children ((GtkTreeModel*) self, NULL);
#line 80 "ease-iterable-models.vala"
	return result;
#line 436 "ease-iterable-models.c"
}


static void ease_iterable_list_store_class_init (EaseIterableListStoreClass * klass) {
	ease_iterable_list_store_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = ease_iterable_list_store_get_property;
	/**
	 * The number of items in this ListStore.
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), EASE_ITERABLE_LIST_STORE_SIZE, g_param_spec_int ("size", "size", "size", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void ease_iterable_list_store_ease_iterable_tree_model_interface_init (EaseIterableTreeModelIface * iface) {
	ease_iterable_list_store_ease_iterable_tree_model_parent_iface = g_type_interface_peek_parent (iface);
}


static void ease_iterable_list_store_instance_init (EaseIterableListStore * self) {
}


/**
 * ListStore with the {@link IterableTreeModel} mixin.
 */
GType ease_iterable_list_store_get_type (void) {
	static volatile gsize ease_iterable_list_store_type_id__volatile = 0;
	if (g_once_init_enter (&ease_iterable_list_store_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (EaseIterableListStoreClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ease_iterable_list_store_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (EaseIterableListStore), 0, (GInstanceInitFunc) ease_iterable_list_store_instance_init, NULL };
		static const GInterfaceInfo ease_iterable_tree_model_info = { (GInterfaceInitFunc) ease_iterable_list_store_ease_iterable_tree_model_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
		GType ease_iterable_list_store_type_id;
		ease_iterable_list_store_type_id = g_type_register_static (GTK_TYPE_LIST_STORE, "EaseIterableListStore", &g_define_type_info, 0);
		g_type_add_interface_static (ease_iterable_list_store_type_id, EASE_TYPE_ITERABLE_TREE_MODEL, &ease_iterable_tree_model_info);
		g_once_init_leave (&ease_iterable_list_store_type_id__volatile, ease_iterable_list_store_type_id);
	}
	return ease_iterable_list_store_type_id__volatile;
}


static void ease_iterable_list_store_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	EaseIterableListStore * self;
	self = EASE_ITERABLE_LIST_STORE (object);
	switch (property_id) {
		case EASE_ITERABLE_LIST_STORE_SIZE:
		g_value_set_int (value, ease_iterable_list_store_get_size (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}




